# Generated by Django 3.2 on 2022-01-24 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Base',
                'verbose_name_plural': 'Bases',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('featured', models.BooleanField(default=False, verbose_name='featured')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='updated')),
                ('available', models.BooleanField(default=True, verbose_name='available')),
                ('has_attributes', models.BooleanField(default=False, verbose_name='attribute')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='image')),
                ('price', models.DecimalField(decimal_places=2, default=9.99, max_digits=4, verbose_name='price')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Sauce',
                'verbose_name_plural': 'Sauces',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='piz002', max_length=6, verbose_name='code')),
                ('price', models.DecimalField(decimal_places=2, default=9.99, max_digits=4, verbose_name='price')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base', to='products.base')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attrs', to='products.product')),
                ('sauce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sauce', to='products.sauce')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='products.size')),
            ],
            options={
                'verbose_name': 'ProductAttribute',
                'verbose_name_plural': 'ProductAttributes',
            },
        ),
    ]
