# Generated by Django 3.2 on 2021-11-30 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211130_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='portion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.portion', verbose_name='portion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.size', verbose_name='size'),
        ),
    ]
