# Generated by Django 3.2 on 2021-12-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20211130_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='piz002', max_length=6, verbose_name='code'),
        ),
    ]
